// Generates supabase/seed.sql from the TS seed arrays.
// Run: pnpm seed:sql  (writes supabase/seed.sql)
// Idempotent: insert ... on conflict do nothing everywhere. Dates are relative
// to generation time so the seed stays fresh.

import { seedInventoryFor, seedOrdersFor, seedSalesDaily } from "../src/lib/data/analytics-seed";
import { seedMenuItems, seedShops } from "../src/lib/data/shops-seed";

const esc = (s: string) => `'${s.replace(/'/g, "''")}'`;
const uuid = (id: string) => `md5(${esc(id)})::uuid`;
const textArray = (arr: string[]) =>
  arr.length === 0 ? `'{}'::text[]` : `'{${arr.map((s) => `"${s.replace(/"/g, '\\"')}"`).join(",")}}'::text[]`;
const jsonb = (v: unknown) => `${esc(JSON.stringify(v))}::jsonb`;

const today = new Date().toISOString().slice(0, 10);
const daysAgo = (date: string) =>
  Math.round((Date.parse(`${today}T00:00:00Z`) - Date.parse(`${date}T00:00:00Z`)) / 86_400_000);
const minutesAgo = (iso: string) => Math.max(0, Math.round((Date.now() - Date.parse(iso)) / 60_000));

const lines: string[] = [
  "-- Generated by scripts/seed-sql.ts — do not edit by hand.",
  "-- Regenerate: pnpm seed:sql",
  "begin;",
];

// shops
lines.push(
  `insert into public.shops (id, slug, name, categories, story, phone, address, city, state, lat, lng, hours, photo, status) values`,
  seedShops
    .map(
      (s) =>
        `  (${uuid(s.id)}, ${esc(s.slug)}, ${esc(s.name)}, ${textArray(s.categories)}, ${esc(s.story)}, ${esc(s.phone)}, ${esc(s.address)}, ${esc(s.city)}, ${esc(s.state)}, ${s.lat}, ${s.lng}, ${jsonb(s.hours)}, ${s.photo === null ? "null" : esc(s.photo)}, ${esc(s.status)})`
    )
    .join(",\n") + `\n  on conflict do nothing;`
);

// menu_items (stable sort = seed order)
lines.push(
  `insert into public.menu_items (id, shop_id, name, description, price_cents, category, flavor_tags, photo, available, bestseller, sort) values`,
  seedMenuItems
    .map(
      (m, i) =>
        `  (${uuid(m.id)}, ${uuid(m.shopId)}, ${esc(m.name)}, ${esc(m.description)}, ${m.priceCents}, ${esc(m.category)}, ${textArray(m.flavorTags)}, ${m.photo === null ? "null" : esc(m.photo)}, ${m.available}, ${m.bestseller}, ${i})`
    )
    .join(",\n") + `\n  on conflict do nothing;`
);

// sales_daily
lines.push(
  `insert into public.sales_daily (shop_id, date, item_id, units, revenue_cents) values`,
  seedSalesDaily
    .map(
      (r) =>
        `  (${uuid(r.shopId)}, current_date - ${daysAgo(r.date)}, ${uuid(r.itemId)}, ${r.units}, ${r.revenueCents})`
    )
    .join(",\n") + `\n  on conflict do nothing;`
);

// inventory (every seeded shop)
const inventoryRows = seedShops.flatMap((s) => seedInventoryFor(s.id));
lines.push(
  `insert into public.inventory (id, shop_id, sku, label, unit, qty, reorder_point, supplier) values`,
  inventoryRows
    .map(
      (i) =>
        `  (${uuid(i.id)}, ${uuid(i.shopId)}, ${esc(i.sku)}, ${esc(i.label)}, ${esc(i.unit)}, ${i.qty}, ${i.reorderPoint}, ${esc(i.supplier)})`
    )
    .join(",\n") + `\n  on conflict do nothing;`
);

// orders + order_items (every seeded shop)
const orders = seedShops.flatMap((s) => seedOrdersFor(s.id));
lines.push(
  `insert into public.orders (id, shop_id, customer_email, customer_name, status, fulfillment, total_cents, placed_at) values`,
  orders
    .map(
      (o) =>
        `  (${uuid(o.id)}, ${uuid(o.shopId)}, ${esc(o.customerEmail)}, ${esc(o.customerName)}, ${esc(o.status)}, ${esc(o.fulfillment)}, ${o.totalCents}, now() - interval '${minutesAgo(o.placedAt)} minutes')`
    )
    .join(",\n") + `\n  on conflict do nothing;`
);

const orderItemRows = orders.flatMap((o) =>
  o.lines.map((l, i) => ({ orderId: o.id, line: i, ...l }))
);
lines.push(
  `insert into public.order_items (order_id, item_id, name, qty, unit_price_cents) values`,
  orderItemRows
    .map(
      (l) =>
        `  (${uuid(l.orderId)}, ${uuid(l.itemId)}, ${esc(l.name)}, ${l.qty}, ${l.unitPriceCents})`
    )
    .join(",\n") + `\n  on conflict do nothing;`
);

lines.push("commit;", "");

// sanity: every menu item references a seeded shop
const shopIds = new Set(seedShops.map((s) => s.id));
const orphans = seedMenuItems.filter((m) => !shopIds.has(m.shopId));
if (orphans.length > 0) {
  console.error(`ERROR: menu items with unknown shop_id: ${orphans.map((m) => `${m.id}->${m.shopId}`).join(", ")}`);
  process.exit(1);
}

console.log(lines.join("\n"));
console.error(
  `seed.sql: ${seedShops.length} shops, ${seedMenuItems.length} menu_items, ${seedSalesDaily.length} sales_daily, ${inventoryRows.length} inventory, ${orders.length} orders, ${orderItemRows.length} order_items`
);
